# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Expense Tracker App Deployment to Surge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: 16
    - run: npm install
    - name: Build react app
      run: npm run build
    - name: Install Surge
      run: npm install --global surge
    - name: Deploy To Surge
      run: surge ./build expense-tracker-app.surge.sh --token ${{secrets.SURGE_TOKEN}}
